### 1. 建立短網址
POST http://localhost:8000/api/v1/shorten
Content-Type: application/json

{
  "original_url": "https://www.riyar.com.tw",
  "expires_at": "2025-12-31 23:59:59",
  "max_clicks": 10
}

HTTP/1.1 201  - Created
host: localhost:8000
connection: close
x-powered-by: PHP/8.4.8
cache-control: no-cache, private
date: Wed, 23 Jul 2025 17:47:03 GMT
content-type: application/json
access-control-allow-origin: *
###
# 請將 GUVFR1 替換為實際的短碼
GET http://localhost:8000/s/GUVFR1
/*

*/
###
# 請將 GUVFR1 替換為實際的短碼
GET http://localhost:8000/api/v1/shorten/GUVFR1/stats